---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
# Employee Materials

- Employee ID
  - Go to Connects in The Claremont Colleges Library Honnold Mudd (H on map)
    - Take picture 
    - Receive ID
  - Go to Story House (14 on map)
    - Get access to infrastructure (doors)
<!--    - Also need a KEY for office room -->
- Email and Username
  - Setup appointment for IT (Angelo)
    - help@cmc.edu
  - Obtain computer access
  - Get put into system
- Workday
  - Send email to Payroll
    - payroll@cmc.edu
  - Log in hours 
    - Talk to Program Assistant
- Health Documents
  - https://www.cmc.edu/healthscreen
- Training with EVERFI
  - Hazard Communication (CA)
  - Protecting Youth
  - Preventing Harassment and Discrimination: Non-Supervisors
  - Injury & Illness Prevention
  - Data Security and Privacy

## Accounts and Software

* CMC Self-Service Account Management    
    - https://mypassword.claremontmckenna.edu/showLogin.cc    
-	CMC Email  
    - https://cmc.edu/mail/office365  
      -	CMC e-mail address: firstname.lastname@claremontmckenna.edu  
      -	Short-hand: firstthreelettersofyourfirstnameandwholelastname@cmc.edu   
-	Dashboards Events  
    -	https://events.cmc.edu/newemployeeusername/home  
-	GitHub  
    -	https://github.com/CMC-QCL  
-	Workday  
    -	https://www.myworkday.com/theclaremontcolleges/d/home.htmld (refer to page 3)  
    -	Kronos (in here)  
-	QCL Home page  
    -	cmc.edu/login  
    -	https://www.cmc.edu/qcl  
-	Box   
    -	https://claremontmckenna.account.box.com/login?redirect_url=%2Ffolder%2F0  
-	Bit.ly  
    -	No account (you will use it a lot)  
    -	https://bitly.com/  
-	Qualtrics  
    -	https://qfreeaccountssjc1.az1.qualtrics.com/login?path=%2FQ%2FMyProjectsSection&product=project-store-proxy  
-	Localist  
    -	https://campusevents.cmc.edu/admin/  
-	Zoom  
    -	https://cmc-its.zoom.us  
-	Teams  
    -	Make sure to download desktop version and mobile as well  
    -	https://teams.microsoft.com  
- Instagram  
    - https://www.instagram.com/cmc.qcl/  
- Facebook  
    - https://www.facebook.com/theQCL  
- Access  
    - https://allocations.access-ci.org/  
- Data Science Capstone  
    - https://sites.cmc.edu/dscapstone/  

_Issues: contact another Graduate Fellow or IT (help@cmc.edu)_  

## Logins and Passwords

|Accounts                           |Username |Password |Talk To       |
|:----------------------------------|:-------:|:-------:|-------------:|
|CMC Self-Service Account Management|         |         |Help desk     |    
|CMC Email                          |         |         |Help desk     |  
|Dashboards Events                  |         |         |Localist acct |   
|GitHub                             |         |         |Dr. Park      |
|Workday                            |         |         |HR            |
|QCL Home page                      |         |         |Communications|
|Box                                |         |         |Dr. Park      |
|Bit.ly                             |         |         |Self          |
|Qualtrics                          |         |         |John          |
|Localist                           |         |         |Communications|
|Zoom                               |         |         |Dr. Park/GradF|
|Teams                              |         |         |Dr. Park      |
|Instagram                          |         |         |Dr. Park/GradF|
|Facebook                           |         |         |Dr. Park/GradF|
|Access                             |         |         |Dr. Park      |
|Data Science Capstone              |         |         |Communications|

_Firefox: bookmark websites_

## Schedule

__Important Dates__  

* Team meetings  
    -	Weekly: Wednesdays 10am -11am  
-	Graduate Fellow meetings  
    -	Talk to Dr. Park to set up best time  
    -	Current Fellow meeting: Tuesday 11am-12pm  
    -	New Time: _______________________  
-	Workshops   
    -	Tuesdays/Wednesdays 3:00pm-5:00pm   
    -	Fridays 1:30pm-3:30pm 
    - Sometimes Saturdays 9:00am-5:00pm
-	Staff Lunch days
    -	Program Coordinator will send out email  
    - food provided  
- Employees Schedule (20 hours a week)  
    -	Talk to Dr. Park
    - flexible and remote


|Monday	|Tuesday  |Wednesday |Thursday |Friday |
|:------|:-------:|:--------:|:-------:|------:|
|DryRuns/BTS 11:30am-1:30pm|Current Fellow meeting: 11am-12pm|Weekly Team meeting: 10am -11am|||
||Workshop: 3:00pm-5:00pm|Workshop: 3:00pm-5:00pm||Workshop: 1:30pm-3:30pm|

_Days off: Holidays and Academic break_

